name: ghconnect
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.1.0
  flutter_animate: ^4.5.2
  unicons: ^3.0.0
  tcard: ^1.3.5

  # State Management
  provider: ^6.1.5
  flutter_riverpod: ^2.6.1

  # Images
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

  # Navigation
  go_router: ^15.1.3

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # UI Components
  smooth_page_indicator: ^1.2.1
  social_auth_buttons: ^2.0.2
  social_auth_btn_kit: ^0.1.3
  awesome_notifications: ^0.10.1

  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^14.0.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

  # Screen Size Adaptation
  flutter_screenutil: ^5.9.3

  # Icon Picker
  flutter_iconpicker: ^3.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
